name: Codes
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.6.2
  - arrow-cpp=17.0.0
  - asgiref=3.8.1
  - async-timeout=4.0.3
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - backoff=2.2.1
  - bcrypt=4.2.1
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cachetools=5.3.3
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - chroma-hnswlib=0.7.6
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - cryptography=43.0.3
  - datasets=2.19.1
  - deprecated=1.2.13
  - dill=0.3.8
  - distro=1.9.0
  - durationpy=0.9
  - fastapi=0.112.2
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.29.0
  - googleapis-common-protos=1.63.2
  - greenlet=3.1.1
  - grpcio=1.62.2
  - h11=0.14.0
  - httpcore=1.0.2
  - httptools=0.6.4
  - httpx=0.27.0
  - httpx-sse=0.4.0
  - huggingface_hub=0.24.6
  - humanfriendly=10.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - jinja2=3.1.4
  - jiter=0.6.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - langchain=0.3.14
  - langchain-chroma=0.1.4
  - langchain-community=0.3.14
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libpulsar=3.5.1
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - marshmallow=3.19.0
  - mdurl=0.1.0
  - mmh3=4.1.0
  - monotonic=1.5
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - networkx=3.3
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - onnxruntime=1.17.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - opentelemetry-api=1.26.0
  - opentelemetry-exporter-otlp-proto-common=1.26.0
  - opentelemetry-exporter-otlp-proto-grpc=1.26.0
  - opentelemetry-instrumentation=0.47b0
  - opentelemetry-instrumentation-asgi=0.47b0
  - opentelemetry-instrumentation-fastapi=0.47b0
  - opentelemetry-proto=1.26.0
  - opentelemetry-sdk=1.26.0
  - opentelemetry-semantic-conventions=0.47b0
  - opentelemetry-util-http=0.47b0
  - orc=2.0.1
  - orjson=3.10.7
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - posthog=3.6.5
  - propcache=0.2.0
  - protobuf=4.25.3
  - pulsar-client=3.5.0
  - pyarrow=17.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic-core=2.27.1
  - pydantic-settings=2.6.1
  - pygments=2.15.1
  - pyjwt=2.9.0
  - pyopenssl=24.2.1
  - pypika=0.48.9
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-flatbuffers=24.3.25
  - python-kubernetes=31.0.0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rsa=4.7.2
  - safetensors=0.4.5
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - sentence-transformers=3.3.1
  - setuptools=75.1.0
  - shellingham=1.5.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - starlette=0.38.2
  - sympy=1.13.3
  - tenacity=8.2.3
  - text-generation=0.7.0
  - threadpoolctl=3.5.0
  - tiktoken=0.8.0
  - tk=8.6.14
  - tokenizers=0.20.1
  - tomli=2.0.1
  - tqdm=4.66.5
  - transformers=4.45.2
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2024b
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - uvloop=0.21.0
  - watchfiles=0.24.0
  - websocket-client=1.8.0
  - websockets=10.4
  - wheel=0.44.0
  - wrapt=1.14.1
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohttp==3.10.11
      - chromadb==0.6.1
      - dataclasses-json==0.5.14
      - dropbox==12.0.2
      - iniconfig==2.0.0
      - langchain-core==0.3.35
      - langchain-huggingface==0.1.2
      - langchain-openai==0.3.1
      - langchain-pinecone==0.2.3
      - langchain-tests==0.3.11
      - langchain-text-splitters==0.3.4
      - langsmith==0.2.10
      - openai==1.59.8
      - openapi-schema-pydantic==1.2.4
      - pinecone==5.4.2
      - pinecone-plugin-inference==3.1.0
      - pinecone-plugin-interface==0.0.7
      - pluggy==1.5.0
      - ply==3.11
      - pydantic==2.10.5
      - pytest==8.3.4
      - pytest-asyncio==0.25.3
      - pytest-socket==0.7.0
      - stone==3.3.1
      - syrupy==4.8.1
